### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by XShockinFireX** [Exxarion/CTF#1]
===BEGIN CRASH DUMP===
eNrtWvtvHDeS/le4YwORgul5P6QJZJxOthPv2ZY2UtaHzQQCu5s901a/0mRrNBv4f7+viuzHyMqe
N8kB90OcwG6+6sWqr4rk/NIzcap6q/FsPluOpovTRb+XSG1elWVe9la/9My+wHAvy00cqF6/lyqt
5Ya6LvIqCbOvjEhyGYoiqTZxJi5uXq9EKvEVgIwWWCeivMpCLI2qJHkdJ7S22MpyNRxerIY/aFXq
4Y38uJPl8CIvVTK8yoM7Zd7FmfLeXR22BrRwqMtgWHB3iu6hZT28wtAVf76FQKrE3IK4Wo5fuAgL
Egz3Vst5v2dKCZ1XP/aejcSvred/3skMNimPpqPx8Uq0s9ZrO229PpjnvSCT2a4jbco424iL1XrN
tlivrTHWa7YGlnYNUFPEtAtZmKpUN1v1OpEbtkxfyLKUe3FOfx8dH0ObZ+PPRL9W5T2EHS9n839X
Wv3bxWVhJp8J004/mi0nj+Sxknovbm+DPAPnKjBH3fGLPC2kif1EXZC32S0Uuf9RBaZ/QKkycQIh
3kna6M2mM8sp1HjkF+r1hFs2tL6YyL+/4tCcU3FEDleqn6u4VLd5Fqijx/r8ERHWzqCgOu799Knf
U/8XCPFbYxXy2Em9VSQTrfq9IA8VSbdYgODa0H/PmeF7mSpxJp6HSgdlXJg4z7wXG2gHkY6OvwHR
xbJdYrax9l5o54eYZlkfHXsvZBheSbM9Wveek9wk9LpnCZyAAP172hCKoyPmfqseYm30UStLX8Cv
1fHxL1iwHDULwNsZ7ExkaifaBVbI5bg71YoZZ7FxqOIW9w/0pJY08nWeQAU0SGxLbGIFXk47REsF
eMmEo8TTZs3wJwUrs8jzzhKzLfMdi2vFePUQKOYMIz3pDOueGHy+FVZLjKx7T7uKs/Oy3dtP1Kz3
jRtuD5b1Hjh1MiQhWntiTU1TT8Z26smEu4Zff00NawrxtfhWGS3MVjmdXrbCiqjMUx5ix8WimVtE
3/OawH8UspRpHeps9d6nP7PLn9nlz+zydHbp9zYqU6VMCMCxRRqxhmAaD0ahuodkfhUnYW81AuiX
ucmDHBOnp/2eLGKeNp4NRpi2iQ2aoy/8gwWlvEtin9YMlkyhyiQVx70PcRbmOy3e34ib879+OP/e
+/v5m0uxGIwFyyKWi9FYHNXTluK7HEnmqlRpXKXiVRgzWpC/IUWKKxncifGxiOcnCzChMnXVmw8W
A2r9UyETrnoTNEd28DbXJMKb9+9v0MGNHRJdk/I0WWl8r8f0rxOYm/2O7UaD0WCOHlmZbV5iyY8/
OXv9SHZlXjAc/kW/yiScPmxyaagKSOUW6TwyL7sdBNDggP2Lo/ghztfrPFP3OqfAuMzU3zX+olSN
8MG0q8vrmw+X3799ia6d8nVsIC+BMvQ5D+8lnCz8r9jojjIH3R2lZoNxV6FeUgVyclIo0+vqNp7+
DqW6rG18/y+a9LbGFBqhAefbVv4gyNNhI9fwQBNSOLrr6olWR73RYHqg3jbfx1k6nqXBoX6T36Nf
dLdeW75fsj9JLA82htv9gxCdsCt1xP6HDL6Dw/+BMhNXuxmMy18m+39KHQff/fCyI37TdajBiOOw
o4FM4irZ/3EKWHrr9bYKf7NPyUR9lFlY5qDVwVLPQcIQ5Y4apjjIq3LY6PmJMINqEYXuWkhOggMA
aaFKEyuCl2dXTUtc5FkUb7jAWZfr7NnrMhavlS/mYjxfTUar6UicX9yIyWi8oHFXKZOFz75FnXlR
ysiI6wrIdy+TzowiL83Z+HQ8nVBnqtK83HtJnMbmbAI0fke9G0n9oTob8Rz5APXkHqKfjTGFiRVy
l3mUBZBtsYFnM9u/28JyIKeNXWv3yfu5UuX+LM86XSVy/1keRcwhN2Er9epAbJllqDwD5UTwZLCN
1b1KVWa0oyiTJN95URJvtqYmaQWUWZzCQQ4709xveqK8BOlGX9eLXBkGSKl1u7gvHKswjqI4qBKz
PxtTO4EoibX6Li+TsO3TSoWwyqztofPa2eu35zfUReoPCkQRloVnX/MfaFKZ3NPyXjl2pQq1AaB7
gUzAVbKp7ZDN1CYvwckY1Ab6zAqo2bxJviHXqTWgjNY462CfJuRt4h2X+OxoVSltZY1FqPVL8SaV
mxhsqTyA+wkUpFqJmhcqUsUFOISjIl0aEdBOGeErEWdBUoUqxIf4zM2J1jVl6TwiAo9pahnhZJZj
pNREUvilkndin1eloyXiSGCzkPOYA/aphA8irkH4PU5ANblhqCKJndJil9PxRxaFkqUgE6fQFaol
e4gv6Ahn1d5tVSaqYlPKEAQG64yCxhJbrTPx7GaL4PYSdEGKRGabCoW0oAMvW8wFmI7RTnLQj//J
NqWlF1sVOC0OF0KAGmVUNtjFd3GhwlgO8nIzpNbwLWLpNo9u31xf3i6mp97kltbBjA2hFY5rKtus
e8Tow1aR7YTJIU8WCmjpqlFsUykzDSeC3XiYrcmSQg58KcNbilqPqqUtYC7hTU5B2AZKy5JxF/16
WxnUXogqe/tAwtj6Xly7ob9Yyc4pSgVBAxeyFi/FfSzF3wgdMIVRokbSFR/PaeH1Fusk+anOIZBj
ZHdL1gfaSsMPkQXgC6zg+dUbzEQqCclU7YAHyfxcq5b8K8ajmg6UFhT6Ah4LpyBR/b1wroTpDr2a
0dYSzz7EsHWewatkGKJ619b5SEy42x3EkRonO0IuAZfzFdkDdkeZLxPakU18j7nAvUqJI8cSAH8M
4pYfUFMRfnvYUDrtrDBKnN9XqU9nn0ic630W3Eh9B6cv7xBDAxrHWSFkF62VpFnbMgeywiswW/cF
w5dwqMJ3Fkh3sJqm/MxmQV6kvrTKEDw0hWlfs9dAH8RXmT8Ab42CCaAOe3vWiEZWteK8iShIaQoF
Y1/E5itYzpS8KlSUUtgRH60VR9AA+ywmZBHWwXNarpgSBaxNaByu3ya5D8NSNSBst+A8R7CUqo30
9wYCiWsryoiZW/S0wQ6ddjELxsYWlGRcvnRdmu0S4ZCGDwGQz5hUBJioOdrthzIVO+0mhx45RQfZ
DHw2LKRNwCsxWjNaMC4boI0M/5+LT5XVvxCeEunvEh7Zr2D+Dq0aeRw1LRBSlEZVWEtDPB+JdKXK
OOd0RIGoiVvAgOxEa4JtDD7AmZAcjGd4CAZlw4xhPM+AXhXdO/Fx/Ndsam2JYihhhKdAt9PWnG+J
BkKvDWOLRcThkvCDMhxPH3w+mXR21S/sV6iAEqG9JyNZrYHt2kYBmFEVulUTtaPVUx8/KZDTemq1
3sjSx+Z7OO4nttqj8HrSquxLJIpbI9waBG4qs4pTblcKVCMVHOG4XwPCI09wrmBBNYpqYEhbFxuI
S5vvuAV32NJ1ZyNIDPjYZaIVnZxWFCw5FFxQOZsxo9ccBp8BI/uKXd0oxbePDnlorRv3upDU2VMo
4bbusSs84T+ddVR3B9squ9PW3m/Z5QkNuZMks1e6ioCdiuM+x2aJAkTbSR7VAFTLtLSIVL3NLkpO
F07Ol7ld9nj7KANQpWSXdSlYLm7aH6AzZyFUu/Bdq3VdzzpGNNCk7n9Jap1lytBeNKUbXCOxadCX
BqcIqkIk1cTIfvAnB0kcgLYwdaMWiXzVJETGmmdd7KpHKPDLvSHafeGNO85MiY/ZeqYWBbAyX1hU
aRMtHxUoy4UW69wG2rXodDINxHc47cC8Z6iF4bgXVz/0sRYS+MCfXRyarYVsju+GvMfkV2LpqoK2
XtBsmM7UgTgPEU9bmURDFPm2hAkV/MwxAkvrf3nWDcgmNXdodYqkVw8UfFQDyaRvA5sYuxu8gYDb
KHZtSvQ/XGVXdZnQ1uxUAdGiHYB+TQV7Vniu2S3IcBZSfrVZuYrjhRhTpeHSCpWUPFyXk5pxbKvq
MnPttmIlxm2RqMVQG2kqOMxwE1jTAtdC3WFan/4Ozg2qriBJbmhiT0w81bkXqcsbHsCIhj3MLfHs
kpVIMbRx5wkoRI5ORVoGl4OTMijJA/qxfbkxHfYwpvlcGo5R3rpn7y9vXq0Eoy7+DyocrjIcrphQ
nBYJl68snuPciNds8fnBbgU4RwBJnK7sRZySIAl5jSHPmYxcCiEos5mJ3IgOw9Tv0pGL+sPuGsNs
IXxdPxn5UqsOs6MxAuUJLn0xwcD4qQFlgsExB61WXSnYHW6IMh2t3L2IUAAmy49Sv91JPsS2p1sC
Aj4CUelEcCCTndxrS9vR6QaKPZYgNhyCoP6WTBEGY3b2wqE5krjhhsRBAmA/PE/zKutmEO0qvloL
0p/EoQMHwJ0+V2L260tlSY+CVhpL4zBtifHp5MnV7J6ZsgdRX1lqvooIyviShiCP9rGhaq9uOthp
ofNa3iNrU3UY03lb0eGt2Lu7BZfMmoqIkSbiu7kaVx0ORlXC03INX/coxuPA2pcPcCUd6OFZIFub
6mNO5ygbXJpetunnPBQVlKEa/RtUsJtBBq034518EPKxXXCCCjjBtA51uBfs5d/LMK50Z5nbB+mk
4yi3S53j0nyUOwRqdEnmVUUIZ+64W5AoaZnw5V2bRuv86yd50CogfpwDTZenP7mimC+QCMBiSM1T
m0qMEcgKU1sacKMpEK4uvrLlcpsmBd08pCoxnEG5ivOrkt2BrhIEp1bNwdmatT201pYdfG5aB+87
GfP9w8+VqpTzPreeUY37PQ1XWomT30StyIsqcdTcN2XeR4TXGUOOh70loe1FpcdermmfaaNTeh2l
GyXXO3boRxeEK2Fr19rhsH9ZVaCWswWtDRfGRltHOVqgsqRVjiERnVNzJ4lR08l9MvVjxKWd4u4m
7f3DymItXZWUUm+F7bUlhHNhG1vuoNJgN0WdR/dXhz1NtjzoLbZFnEV566TbnDyTWQ46t5mo81i+
LM/2KZ1iOH417KsbQcnP3LBoh1lg+mWGkJsNkqu7+GiulKgEpl8L3D2tjZWHyOmn5KHnElvFouqR
lDttg4oPOI97+lgJ98FD2Fk68iLA6NNDwujzGfgnomgBqS4pujenXELUtb89gNXXw3yyeuoiliOP
M5Lm7E9+nKIoiCGoS9cd0ZkrC8Bfgq63yU85O7TcVoIuuFeTb5b9+enDuD99mPYn34y/CZFVbYge
0QtJQOF0djISG2ymtq3Z/JjvqWN38dzeVLs3HvVgVEaW4qcwevLuPN/6AUqObfsrJJlg12XZdthf
S9XPRdJ0FwPgN81YFCeIBX66HY/5US0yRTO6hfPZ1yoSlWqgZuijbp7i6A0Y5dq+MM3o9dVbpjmh
t+TQDxoiRVC2gn2vInfgwvjzNzCxiqITPwwWc3/kKxmdRDMZqkU0WkQnsxO1CGfTMApPJgvxvEeP
Sto+pzly8E2yQtjRNd3rnxN+6nZfYj4gTb1Q3QuP3pMmo/loik9mPw0WJyf+wveD6SicLmQ0lcF0
FoXhzF/6c395sozUHH+YvcnvVAaEc9ajV/W4sL8MmAxm1LTP/PatEt8Pne0N85SGRqPpeDw5xfjV
y0v3LjizPz+g36HZ1WzFa65H//vd24bbLgwfGnpd2vims0lHMPTsyth0ej4oeVeqyG4SmwrVb0uC
rRU3s6lh1NT+ZsGz8mnGAN0u8e3Ne9Oxl/zwQu/9RKNwlxZOpzEZBSeK2zA3wJCGVWp9ztH4B8Hu
5RXDPqYsyTzE//Wr3qdP/wObEWFu
===END CRASH DUMP===

**Comment by Exxarion** [comment]
This plugin is no where near completed yet. It is not ready for any live testing.
